### ISSUE TITLE
feat: blue tick mark near the header is aligning according to designation length. Its not fixed

### ISSUE THREAD

**Issue by Jeya-rosini** [anburocky3/post-mockup-app#3]
- While we type our designation, if its is small the blue tick is perfect in its place
- But when we have a bigger designation, the position got aligned according to the length of the designation we type
- We have to make the designation in a fixed position, It will make the post more real
![jeya_2024_2_19-17_15_19_quote](https://github.com/anburocky3/post-mockup-app/assets/143939511/ef80d865-4c84-4ba3-af01-1c7af893daac)

> I have added a reference image for more clarification

**Comment by anburocky3** [comment]
Thanks for the valuable report. We have identified and fixed it. 
e030a5ba7af9707196e24c67e89245488f52e007

**Comment by Jeya-rosini** [comment]
Thank you. I have checked it works nice
